### PR TITLE
update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by itisaby**

### CODE REVIEW

**Review by jensg-st — APPROVED** [review]

**Comment by jensg-st** [comment]
To merge the PR all commits need to be signed. The second last has not been signed. The last one is now though. This means usually you need to rebase to sign them. https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

**Comment by itisaby** [comment]
Alright, I am doing it right now

**Comment by itisaby** [comment]
I used this command 
`git rebase --exec 'git commit --amend --no-edit -n -S'`

**Comment by alankm** [comment]
Could it be that it's signed okay but you haven't added your signing key to your Github account?

**Comment by itisaby** [comment]
It is configured with my GitHub account

**Comment by jensg-st** [comment]
I'm assuming that is not getting fixed in this PR. Just open a new one when ready.

**Pull request closed without merging**
