### PR TITLE
update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by itisaby**

### CODE REVIEW

**Review by jensg-st — APPROVED** [review]

**Comment by jensg-st** [comment]
The commit is not signed. Can you please sign it?

**Comment by itisaby** [comment]
I did it using gitsign @jensg-st, Still I will check it again

**Comment by jensg-st** [comment]
> I did it using gitsign @jensg-st, Still I will check it again

-s -S will do it

**Comment by itisaby** [comment]
cool on it

**Comment by itisaby** [comment]
I have created another PR making proper signing commit.

**Pull request closed without merging**
