### PR TITLE
db init container

### PR DESCRIPTION
**Pull request by jensg-st**
Signed-off-by: Jens Gerke <jens.gerke@direktiv.io>

## Description

This PR is introducing an init-container for the flow component. In case of database changes between versions it can run the updates per db schema generation.

### CODE REVIEW

**Comment by alankm** [comment]
@jensg-st

I've pushed a commit that stores generation information in the database. It has been tested, but not extensively. But I thought I'd comment here in case you wanted to review it. 

I am aware that this may need tweaks in future to avoid race conditions when multiple pods run the upgrader in parallel.

**Comment by jalfvort** [comment]
Code looks good. I did a test upgrading from `v0.5.x` . Upgrader executed with no problems and I see changes on my tables, but I think some steps are missing in the `0.6.0` upgrader as flow is now stuck in crash loop.
### Relevant logs
```sh
> kc logs direktiv-flow-55cf477f9c-6r7zz updatedb
2022/01/11 00:35:17 Checking database for schema updates...
2022/01/11 00:35:17 Current database generation: 0.5.10
2022/01/11 00:35:17 Updating to generation 0.6.0
2022/01/11 00:35:17 Updating to generation 0.6.0 finished
```

```sh
> kc logs direktiv-flow-55cf477f9c-6r7zz flow
{"level":"debug","timestamp":"2022-01-11T00:41:13Z","caller":"flow/server.go:93","msg":"Initializing telemetry.","component":"flow","build":"d83d554"}
{"level":"debug","timestamp":"2022-01-11T00:41:13Z","caller":"flow/server.go:102","msg":"Initializing secrets.","component":"flow","build":"d83d554"}
{"level":"debug","timestamp":"2022-01-11T00:41:13Z","caller":"flow/server.go:109","msg":"Initializing locks.","component":"flow","build":"d83d554"}
{"level":"debug","timestamp":"2022-01-11T00:41:13Z","caller":"flow/server.go:119","msg":"Initializing database.","component":"flow","build":"d83d554"}
{"level":"error","timestamp":"2022-01-11T00:41:13Z","caller":"flow/main.go:166","msg":"sql/schema: alter table \"events\": pq: column \"created_at\" of relation \"events\" contains null values","component":"flow","build":"d83d554"}
```

**Comment by alankm** [comment]
Good catch. Indeed, the code doesn't handle that table. I'll fix that now.

**Review by jalfvort — APPROVED** [review]
Amazing

**Pull request merged**
