### PR TITLE
[DIR-1109] Remove revisions Refs and Tags

### PR DESCRIPTION
**Pull request by sir-hassan**
## Description

This PR removes all revsions, tags, references features completely from the API.

1- Following endpoints are removed:

- POST /api/namespaces/{namespace}/tree/{workflow}?op=save-workflow
- POST /api/namespaces/{namespace}/tree/{workflow}?op=discard-workflow
- GET /api/namespaces/{namespace}/tree/{workflow}?op=tags
- GET /api/namespaces/{namespace}/tree/{workflow}?op=refs
- GET /api/namespaces/{namespace}/tree/{workflow}?op=revisions
- DELETE /api/namespaces/{namespace}/tree/{workflow}?op=delete-revision
- POST /api/namespaces/{namespace}/tree/{workflow}?op=tag
- POST /api/namespaces/{namespace}/tree/{workflow}?op=untag
- POST /api/namespaces/{namespace}/tree/{workflow}?op=retag
- POST /api/namespaces/{namespace}/tree/{workflow}?op=validate-ref

2- Following endpoints are not longer accept tags or refs in the path:
- POST /api/namespaces/{namespace}/tree/{workflow}?op=execute
- POST /api/namespaces/{namespace}/tree/{workflow}?op=wait
- GET /api/namespaces/{namespace}/tree/{workflow}?op=wait
- GET /api/namespaces/{namespace}/tree/{nodePath}

3- Endpoints to list instances, have field `revision` removed from the response.

4- Following endpoints:
- PUT /api/namespaces/{namespace}/tree/{workflow}?op=create-workflow
- POST /api/namespaces/{namespace}/tree/{workflow}?op=update-workflow
- GET /api/namespaces/{namespace}/tree/{nodePath}
Have these changes in the responses:
- new field `source` of type bytes added. 
- field `revision` removed.

### CODE REVIEW

**Comment by sir-hassan** [comment]
@stefan-kracht , @sebxian , Please take care.

**Comment by stefan-kracht** [comment]
@sir-hassan I have one issue that currently breaks one feature for us. To come directly to the point: 

- I request the content of a file via `api/namespaces/test/tree/my.yaml`
- the response has a `node.updatedAt` attribute
- this attribute is always the same as the `createdAt`

This is not how it should work, right?

We used `revision.createdAt` before, to show the user, when last changes to that file was made

CleanShot 2024-01-22 at 13 53 03@2x

**Comment by sir-hassan** [comment]
@stefan-kracht , @sebxian , No worries for the failing tests, I will fix them before merging.

**Review by sebxian — APPROVED** [review]
Good work, @stefan-kracht!

EDIT: I pushed some very minor changes: eb4b3f8db5335390a5860b894d63e1fe7720dba2.

This just cleans up a linter warning and removes a named function in tests that isn't reused, so it seemed better to remove that code block to the one test where it is needed.

@sir-hassan I have reviewed all changes in `ui/` and tested the updated routes. It looks good to me. I can also confirm the playwright e2e tests run successfully.

**Pull request merged**
